on:
  push:
    branches:
      - develop
      - master
    paths:
      - "**/src/**"

jobs:
  workflow-called:
    uses: demo-hell/reusables-workflows-pbi/.github/workflows/pbi.yml@master
    secrets: inherit
    with:
      FABRIC_WORKSPACE_ID: ${{ github.ref == 'refs/heads/master' && vars.FABRIC_WORKSPACE_ID_PRD || vars.FABRIC_WORKSPACE_ID_DEV }}
